#!/usr/bin/env node
// gen-test - turn a CDP_RECORD session log (JSONL) into a faithful e2e/tests/<slug>.cdp.mjs.
//
// Session capture v0 (web path): the browser-driver drives a flow once with
// CDP_RECORD=<log> set (cdp.mjs appends one JSON op per successful action), then runs
// this to scaffold a committed cdp-client test whose REPLAY uses selectors that
// actually worked — then it adds real assertions and verifies with run_spec.
//
// Dependency-free (Node built-ins only). logToTest() is PURE (no I/O) so it is unit-
// testable without Chrome. Excluded from oxlint/oxfmt (vendored, uses semicolons).

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname } from 'path';
import { fileURLToPath } from 'url';

// JS string literal for embedding inside single quotes in the emitted source.
function q(s) {
  return "'" + String(s ?? '').replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n') + "'";
}

// Map ONE recorded op to ONE cdp-client call line (2-space indented, inside try{}).
// op names match cdp-client method names 1:1 (nav->goto is the only rename).
function opToCall(entry) {
  switch (entry.op) {
    case 'nav': return `  await b.goto(${q(entry.url)})`;
    case 'fill': return `  await b.fill(${q(entry.selector)}, ${q(entry.text)})`;
    case 'click': return `  await b.click(${q(entry.selector)})`;
    case 'type': return `  await b.type(${q(entry.text)})`;
    case 'press': return `  await b.press(${q(entry.key)})`;
    case 'clickAt': return `  await b.clickAt(${Number(entry.x)}, ${Number(entry.y)})`;
    default: return `  // (skipped unknown op: ${JSON.stringify(entry)})`;
  }
}

/**
 * PURE. Build the full source of an e2e/tests/<slug>.cdp.mjs from a recorded op log.
 * entries: array of { op, ... } (see cdp.mjs recordOp). opts.name -> slug (header),
 * opts.baseUrl -> documented default for E2E_BASE_URL. Replays each op via cdp-client,
 * then a clearly-marked TODO + two safe scaffolded assertions (title non-empty, url
 * is a string), prints PASS, exits 0 — matching the committed-test shape exactly.
 */
export function logToTest(entries, opts = {}) {
  const name = opts.name || 'recorded-flow';
  const baseUrl = opts.baseUrl || '';
  const list = Array.isArray(entries) ? entries : [];
  const replay = list.length
    ? list.map(opToCall).join('\n')
    : '  // (no recorded actions)';
  const baseComment = baseUrl
    ? `// recorded against ${baseUrl} — runs relative to process.env.E2E_BASE_URL`
    : `// runs relative to process.env.E2E_BASE_URL`;

  return `// e2e test: ${name}
// GENERATED by gen-test.mjs from a recorded CDP session (selectors are ones that worked).
// Replays the captured flow, then asserts. EDIT the assertions below for the real guarantee.
${baseComment}
import { open } from '../cdp-client.mjs'
import assert from 'node:assert/strict'

const b = await open({ baseURL: process.env.E2E_BASE_URL })
try {
  // --- replayed actions (captured) ---
${replay}

  // --- scaffolded assertions (safe defaults) ---
  assert.ok((await b.title()).length >= 0, 'page has a title')
  assert.equal(typeof (await b.url()), 'string', 'page has a url')

  // TODO: add assertions (e.g. await b.waitForText('main', /.../i))
  await b.shot(${q(name + '-01.png')})
  console.log('PASS')
} finally {
  await b.close()
}
`;
}

// --- CLI wrapper: node gen-test.mjs --from <log.jsonl> --out <path> [--name <slug>] [--base <url>]
function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--from') out.from = argv[++i];
    else if (a === '--out') out.out = argv[++i];
    else if (a === '--name') out.name = argv[++i];
    else if (a === '--base') out.base = argv[++i];
  }
  return out;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.from || !args.out) {
    console.error('Usage: node gen-test.mjs --from <log.jsonl> --out <path> [--name <slug>] [--base <url>]');
    process.exit(1);
  }
  const raw = readFileSync(args.from, 'utf8');
  const entries = raw
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l) => {
      try { return JSON.parse(l); } catch { return null; }
    })
    .filter(Boolean);
  const source = logToTest(entries, { name: args.name, baseUrl: args.base });
  mkdirSync(dirname(args.out), { recursive: true });
  writeFileSync(args.out, source);
  console.error(`gen-test: wrote ${args.out} (${entries.length} recorded op(s))`);
}

// Run main() only when executed directly (not when imported by the unit test).
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
