name: Shippie 🚢 CI

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write
  contents: read
  actions: read
  models: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_SHA: ${{ github.sha }}
      BASE_SHA: ${{ github.event.pull_request.base.sha }}
      OPENAI_API_KEY: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i

      - name: Lint check
        run: bun check

      - name: Type check
        run: bun check:types

      - name: Build package
        run: bun run build

      - name: Run unit tests
        run: bun test:unit

      - name: Run shippie review action
        uses: ./
        with:
          MODEL_STRING: openai:gpt-4.1-mini
          REVIEW_LANGUAGE: English
          BASE_URL: https://models.github.ai/inference

      - name: Run shippie review
        run: bun review --platform=github --modelString=openai:gpt-4.1-mini --baseUrl=https://models.github.ai/inference --debug

      - name: Run e2e tests (optional)
        run: bun test:e2e
