name: Release Package
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: node

  publish-package:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created  }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js for npm
        uses: actions/setup-node@v4
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: 💫 Install dependencies
        run: npm install --no-audit --no-fund

      - name: 🏡 Build package
        run: npm run build

      - name: 🚀 Publish shippie
        run: npm publish --access public
